name: Publish Site
on:
  push:
      branches:
        - master
      paths:
        - 'README.md'
        - 'site/default.html'
        - 'site/generate.site.mjs'

jobs:
  main:
    name: Publish Site
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: linz/action-typescript@v3

      - name: Generate page
        run: |
          ./site/get.assets.sh
          node site/generate.site.mjs

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_CI_ROLE }}

      - name: AWS Configure ODR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ODR_DATAMANAGER_ROLE }}
          role-chaining: true

      - name: Publish page to S3
        run: |
          aws s3 cp index.html s3://nz-imagery/index.html --content-type text/html